/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author John
 */
public class ViewDetailsDialog extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetailsDialog
     */
    public ViewDetailsDialog(java.awt.Frame parent, boolean modal, int employeeNumber) {
        super(parent, modal);
        initComponents();
        
        setTextFieldsToOriginalInformation(employeeNumber);
        
        
    }
    
    public ViewDetailsDialog(java.awt.Dialog dialog, boolean modal, int employeeNumber) {
        super(dialog, modal);
        initComponents();
        
        setTextFieldsToOriginalInformation(employeeNumber);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hourlyWageLabel = new javax.swing.JLabel();
        hoursPerWeekLabel = new javax.swing.JLabel();
        weeksPerYearLabel = new javax.swing.JLabel();
        annualSalaryLabel = new javax.swing.JLabel();
        employeeNumberTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        hourlyWageTextField = new javax.swing.JTextField();
        hoursPerWeekTextField = new javax.swing.JTextField();
        weeksPerYearTextField = new javax.swing.JTextField();
        annualSalaryTextField = new javax.swing.JTextField();
        partTimeRadioButton = new javax.swing.JRadioButton();
        fullTimeRadioButton = new javax.swing.JRadioButton();
        closeButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        deductionRateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        annualGrossIncomeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        annualNetIncomeTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        workLocationTextField = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 102))); // NOI18N

        jLabel2.setText("Employee Number:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Part or Full Time Status:");

        hourlyWageLabel.setText("Hourly Wage:");

        hoursPerWeekLabel.setText("Hours Per Week:");

        weeksPerYearLabel.setText("Weeks Per Year:");

        annualSalaryLabel.setText("Annual Salary:");

        employeeNumberTextField.setEditable(false);

        firstNameTextField.setEditable(false);

        lastNameTextField.setEditable(false);

        hourlyWageTextField.setEditable(false);

        hoursPerWeekTextField.setEditable(false);

        weeksPerYearTextField.setEditable(false);

        annualSalaryTextField.setEditable(false);

        partTimeRadioButton.setText("Part-Time");
        partTimeRadioButton.setEnabled(false);
        partTimeRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                partTimeRadioButtonStateChanged(evt);
            }
        });

        fullTimeRadioButton.setText("Full-Time");
        fullTimeRadioButton.setEnabled(false);
        fullTimeRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fullTimeRadioButtonStateChanged(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Deduction Rate:");

        deductionRateTextField.setEditable(false);

        jLabel1.setText("Annual Gross Income:");

        annualGrossIncomeTextField.setEditable(false);

        jLabel7.setText("Annual Net Income:");

        annualNetIncomeTextField.setEditable(false);

        jLabel8.setText("Gender:");

        jLabel9.setText("Work Location:");

        genderTextField.setEditable(false);
        genderTextField.setText("jTextField1");

        workLocationTextField.setEditable(false);
        workLocationTextField.setText("jTextField2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(66, 66, 66)
                                    .addComponent(partTimeRadioButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(weeksPerYearLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(weeksPerYearTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hoursPerWeekLabel)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(annualSalaryLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(annualSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hourlyWageLabel)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(hourlyWageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(hoursPerWeekTextField))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fullTimeRadioButton)
                            .addGap(81, 81, 81))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameTextField)
                                .addComponent(firstNameTextField)
                                .addComponent(deductionRateTextField)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(employeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(workLocationTextField)
                                .addComponent(genderTextField))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(annualNetIncomeTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(annualGrossIncomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(closeButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(deductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(workLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(partTimeRadioButton)
                    .addComponent(fullTimeRadioButton))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourlyWageLabel)
                    .addComponent(annualSalaryLabel)
                    .addComponent(hourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annualSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursPerWeekLabel)
                    .addComponent(hoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weeksPerYearLabel)
                    .addComponent(weeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(annualGrossIncomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(annualNetIncomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(closeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTextFieldsToOriginalInformation(int employeeNumber){
        
        //Get employee from employee Number
        EmployeeInfo employee = MainJFrame.employeeHashTable.readFromTable(employeeNumber);
        
        //Get and set String versions of attributes to text fields
        employeeNumberTextField.setText(Integer.toString(employee.employeeNumber));
        firstNameTextField.setText(employee.firstName);
        lastNameTextField.setText(employee.lastName);
        deductionRateTextField.setText(Double.toString(employee.deductionRate));
        
        genderTextField.setText(employee.getGender());
        workLocationTextField.setText(employee.getWorkLocation());
        
        if(employee instanceof PTEmp){
            //Automatically calls partTimeRadioButtonStateChanged and updates PTEmp options
            partTimeRadioButton.setSelected(true);
            
            hourlyWageTextField.setText(Double.toString(((PTEmp)employee).getHourlyWage()));
            hoursPerWeekTextField.setText(Double.toString(((PTEmp)employee).getHoursPerWeek()));
            weeksPerYearTextField.setText(Double.toString(((PTEmp)employee).getWeeksPerYear()));
            
            annualGrossIncomeTextField.setText(Double.toString(((PTEmp)employee).calcAnnualGrossIncome()));
            annualNetIncomeTextField.setText(Double.toString(((PTEmp)employee).calcAnnualNetIncome()));
        }
        else{//Instance of FTEmp
            //Automatically calls partTimeRadioButtonStateChanged and updates PTEmp options
            fullTimeRadioButton.setSelected(true);
            
            annualSalaryTextField.setText(Double.toString(((FTEmp)employee).getYearlySalary()));
            
            annualGrossIncomeTextField.setText(Double.toString(((FTEmp)employee).calcAnnualGrossIncome()));
            annualNetIncomeTextField.setText(Double.toString(((FTEmp)employee).calcAnnualNetIncome()));
            
        }
        
        
    }
    
    private void partTimeRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_partTimeRadioButtonStateChanged
        // TODO add your handling code here:

        //Update Options when partTimeRadioButton state changes
        partOrFullTimeOptionsVisibilityUpdate();
    }//GEN-LAST:event_partTimeRadioButtonStateChanged

    private void fullTimeRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fullTimeRadioButtonStateChanged
        // TODO add your handling code here:
        //Update Options when fullTimeRadioButton state changes
        partOrFullTimeOptionsVisibilityUpdate();
    }//GEN-LAST:event_fullTimeRadioButtonStateChanged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        //Closes view Employee Dialog Box
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void partOrFullTimeOptionsVisibilityUpdate(){
        
        if(checkPartTimeStatus() == true){//If Part Time Employee
            
            //Set all full time options invisible; text fields remain
            annualSalaryLabel.setVisible(false);
            annualSalaryTextField.setVisible(false);
            
            //Set all part time options visible
            hourlyWageLabel.setVisible(true);
            hoursPerWeekLabel.setVisible(true);
            weeksPerYearLabel.setVisible(true);
            
            hourlyWageTextField.setVisible(true);
            hoursPerWeekTextField.setVisible(true);
            weeksPerYearTextField.setVisible(true);
        }
        
        else{//New Employee is Full Time Employee
            
            //Set all part time options invisible; text fields remain
            hourlyWageLabel.setVisible(false);
            hoursPerWeekLabel.setVisible(false);
            weeksPerYearLabel.setVisible(false);
            
            hourlyWageTextField.setVisible(false);
            hoursPerWeekTextField.setVisible(false);
            weeksPerYearTextField.setVisible(false);
            
            //Set all full time options true
            annualSalaryLabel.setVisible(true);
            annualSalaryTextField.setVisible(true);
        }
        
    }
    
    private boolean checkPartTimeStatus(){//Returns true for part time, false for full time
        return partTimeRadioButton.isSelected();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewDetailsDialog dialog = new ViewDetailsDialog(new javax.swing.JFrame(), true, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annualGrossIncomeTextField;
    private javax.swing.JTextField annualNetIncomeTextField;
    private javax.swing.JLabel annualSalaryLabel;
    private javax.swing.JTextField annualSalaryTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField deductionRateTextField;
    private javax.swing.JTextField employeeNumberTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JRadioButton fullTimeRadioButton;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JTextField hourlyWageTextField;
    private javax.swing.JLabel hoursPerWeekLabel;
    private javax.swing.JTextField hoursPerWeekTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton partTimeRadioButton;
    private javax.swing.JLabel weeksPerYearLabel;
    private javax.swing.JTextField weeksPerYearTextField;
    private javax.swing.JTextField workLocationTextField;
    // End of variables declaration//GEN-END:variables
}
